### ISSUE TITLE
[1.19.2] Crash when returning to overworld from the end in survival.

### ISSUE THREAD

**Issue by Sazuzaki** [dragoni7/RpgSkillable#10]
https://pastebin.com/M0hSZfaU

Nether portals work fine, only happens when I'm returning from the end in survival.

After further testing in creative, returning through the end portal resets all of your skills.

**Comment by norfaremc** [comment]
Any idea on when the update for this will be released? Right now 10 of my players cannot join the server due to this issue. We are on the latest version of the mod, but this issue is still persistent. It doesn't wipe data, but they are completely unable to join. It joins and immediately disconnects them. We managed to get someone back by tp'ing them to us, but everyone else disconnects too fast for us to bring them back.

**Comment by gund** [comment]
This is still an issue and players cannot join the server after returning from the End.
Also it does not happen to the first player who kills the dragon and teleports back but to all others who are teleporting back afterwards.
UPDATE: Had to delete this mod from the server to allow players to join again as it's unplayable until fixed.

**Comment by norfaremc** [comment]
Assuming this mod development is now dead or abandoned. Removed from our modpacks as well.

**Comment by BURNINGSHADOW278** [comment]
Wait so why was this closed/completed? We have the same issue and I don't think there is any fix apart from removing the mod... so it's not really resolved. Kind of sucks to have to remove the whole mod just for that.

**Comment by BURNINGSHADOW278** [comment]
> Any idea on when the update for this will be released? Right now 10 of my players cannot join the server due to this issue. We are on the latest version of the mod, but this issue is still persistent. It doesn't wipe data, but they are completely unable to join. It joins and immediately disconnects them. We managed to get someone back by tp'ing them to us, but everyone else disconnects too fast for us to bring them back.

(Btw you can fix this by changing the player data for those players, in particular "their coordinates" though maybe putting them in creative mode also works.)  Though obviously removing the mod completely is also a solution.
