### ISSUE TITLE
axe tool may useless

### ISSUE THREAD

**Issue by athenaxp** [dragoni7/RpgSkillable#2]
I created a new character for the first time. I couldn't use an axe.
it say your right arm struggles to wield the item.
wood axe!!! 

I can't cut down the tree with another tool.

<img src="https://sv1.picz.in.th/images/2023/02/17/LHEdnD.jpg" alt="LHEdnD.jpg" border="0" />

**Comment by dragoni7** [comment]
Yes, this is intended. You change the requirement for the wooden axe by using the config and setting "useAttributeLocks" to false. The mode will then only add restrictions based off the values in "skillLocks".
I am also working on an update to add an ignore item list that will include the wooden axe.

**Comment by athenaxp** [comment]
> Yes, this is intended. You change the requirement for the wooden axe by using the config and setting "useAttributeLocks" to false. The mode will then only add restrictions based off the values in "skillLocks". I am also working on an update to add an ignore item list that will include the wooden axe.

oh i got it.thank for help.
