### ISSUE TITLE
User Config Options

### ISSUE THREAD

**Issue by NyteNakoa** [dragoni7/RpgSkillable#5]
I really would like a built-in way to config the settings for this mod. I like how it functions and I enjoy it's playstyle, but I incredibly dislike the fact that I'm forced to use only specific kinds of armor sets at a time all because of the fact that there is only 66 allowed skills at once.

-
If I had the ability to config files, I would;
-
1. Make every skill max out at 36, not 31. 6 x 6 = 36, 6 levels per skill.
2. Increase the max skills limit to 216; allowing the player to unlock every skill at their disposal.
3. Make skills more expensive to upgrade with XP, further prolonging the grind and making the game more drawn out.
4. Reducing the requirements to use stone tools and increasing them for higher quality tools. There's no reason I should be forced to get strength 10 just to use a stone axe, when I can already use an iron axe at that point??
5. Figure out and/or entirely remove the scaling for modded items. No reason why I should need dexterity 20 to use an armor set that performs equal to iron armor. 

-
Additional note: Make the larvae craftable. Frequently being able to change your skillset around with no punishment or loss to XP would allow people to much easier tolerate the skill cap.
-
These are things I would change for my case specifically because I'm a solo player doing a one-life hardcore challenge in an RPG setting, and being limited by these things are way more annoying then they are fun. Obviously, this mod scales differently based on the friends you have. 4 friends allows you to have one person dedicated to each category, versus one person that needs to cover them all.. doesn't entirely add up.

Until these are fixed, I'll likely go with a different mod or no mod at all
I did try to edit the config in files for myself specifically but I stopped fiddling with it because I know nothing about it, so we'll see as time goes on.

**Comment by dragoni7** [comment]
Many of these things can be changed in the config for now. For example to increase the individual skill cap and total skill cap you'll want to change these lines in the config:

#Maximum level each skill can be upgraded to.
#Range: > 2
maximumLevel = 31
#Maximum levels the player can have. This is the sum of all skill levels.
#Range: > 6
maximumLevelTotal = 66

As for the scaling costs for items, the values for that can be changed by editing the list after "attributeSkillLocks". For example, changing the entry "generic.attack_damage strength:1" from 1 to 0.5 will reduce the costs by half, so the stone axe would then cost 5 strength if it was 10 before.

Aside from that, I am planning on changing many features of the mod for reasons you've pointed out.
